<?php

/**
 * @file
 * Contains alergs_contratosativos.module.
 */

/**
 * Implements hook_theme().
 */
function alergs_contratosativos_theme($existing, $type, $theme, $path)
{
  return [

    'alergs_contratosativos_contratos_ativos' => [
      'render element' => 'children',
      'template' => 'contratos-ativos',
      'path' => $path . '/templates',
      'variables' => [
        'contratos' => [],
      ],
    ],

  ];
}
