<?php

/**
 * @file
 * Contains alergs_agenda.module.
 */

use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\HttpFoundation\JsonResponse;
use \Drupal\user\Entity\User;



/**
 * Implements hook_theme().
 */
function alergs_agenda_theme($existing, $type, $theme, $path) {
  
  return [		
    'alergs_agenda_agenda' => [
      'render element' => 'children',
      'template' => 'agenda',
      'path' => $path . '/templates',
      'variables' => [
        'link_cultural' => [],
      ],
    ],
    'alergs_agenda_widget' => [
      'render element' => 'children',
      'template' => 'agendawidget',
      'path' => $path . '/templates',
      'variables' => [
       
      ],
    ]
  ];

}