<?php

/**
 * @file
 * Contains alergs_opine.module.
 */

use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\HttpFoundation\JsonResponse;
use \Drupal\user\Entity\User;



/**
 * Implements hook_theme().
 */
function alergs_opine_theme($existing, $type, $theme, $path) {

  return [		
    'alergs_opine_consulta_publica' => [
      'render element' => 'children',
      'template' => 'consulta-publica',
      'path' => $path . '/templates',
      'variables' => [
        'user_name' => [],
      ],
    ],
  ];

}