<?php
/**
 * @file
 * Contains alergs_newsletter.module.
 */

/**
 * Implements hook_theme().
 */
function alergs_newsletter_theme($existing, $type, $theme, $path)
{
  return [
    // Form newsletter
    'alergs_newsletter_form_newsletter_footer_block' => [
      'render element' => 'children',
      'template' => 'form-newsletter-footer-block',
      'path' => $path . '/templates',
      'variables' => [
        'variable' => NULL
      ],
    ],
  ];
}